name: Build Docker Container and push to DO Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test_django_job:
    uses: JuanLadeira/kuber-django/.github/workflows/test_django.yaml@master
  docker_build_job:
    runs-on: ubuntu-latest
    needs: [test_django_job]
    defaults:
      run:
        working-directory: ./web
    env:
      CLUSTER_NAME: k8s-django
      IMAGE_NAME: django-k8s-web
      CONTAINER_NAME: django-k8s-web
      DEPLOYMENT_NAME: django-k8s-web-deployment
      ENV_SECRETS: django-k8s-web-prod-env
      
 
    steps:
    - name: Checkout codes
      uses: actions/checkout@v3
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{secrets.DO_API_TOKEN_KEY}}
    - name: Login to Digital ocean container registry with short-lived credencials
      run: doctl registry login --expiry-seconds 1200
    - name: build container image
      working-directory: ./web
      run: |
        docker build -f Dockerfile -t registry.digitalocean.com/${{env.CLUSTER_NAME}}/${{env.IMAGE_NAME}}:latest -t registry.digitalocean.com/${{env.CLUSTER_NAME}}/${{env.IMAGE_NAME}}:${GITHUB_SHA::7} . 
    - name: push image to container registry.
      run:
        docker push registry.digitalocean.com/${{env.CLUSTER_NAME}}/${{env.IMAGE_NAME}} --all-tags
    - name: K8s cluster kubeconfig file with/ short-lived creds
      run: | 
        doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{env.CLUSTER_NAME}}
    - name: Update Deployment secrets
      run: |
        cat << EOF >> web/.env.prod
        ENV_ALLOWED_HOSTS=143.244.208.107
        REGION=TEXAS
        DJANGO_SUPERUSER_USERNAME={{ secrets.DJANGO_SUPERUSER_USERNAME }}
        DJANGO_SUPERUSER_PASSWORD={{ secrets.DJANGO_SUPERUSER_PASSWORD }}
        DJANGO_SUPERUSER_EMAIL={{ secrets.DJANGO_SUPERUSER_EMAIL }}
        DJANGO_SECRET_KEY={{ secrets.DJANGO_SECRET_KEY }}
        POSTGRES_DB={{ secrets.POSTGRES_DB }}
        POSTGRES_PASSWORD={{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_USER={{ secrets.POSTGRES_USER }}
        POSTGRES_HOST={{ secrets.POSTGRES_HOST }}
        POSTGRES_PORT={{ secrets.POSTGRES_PORT }}
        EOF
        kubectl delete secret ${{env.ENV_SECRETS}}
        kubectl create secret generic ${{env.ENV_SECRETS}} --from-env-file= web/.env.prod

    - name: Update Deployment image
      run: |
        kubectl set image deployment/${{env.DEPLOYMENT_NAME}} ${{env.CONTAINER_NAME}}=registry.digitalocean.com/${{env.CLUSTER_NAME}}/${{env.IMAGE_NAME}}:${GITHUB_SHA::7}
    - name: Wait for rollout to finish
      run: |
        kubectl rollout status deployment/${{env.DEPLOYMENT_NAME}}
    - name: Migrate database command
      run: |
        export SINGLE_POD_NAME=$(kubectl get pod -l app=${{env.DEPLOYMENT_NAME}} -o jsonpath="{.items[0].metadata.name}")
        kubectl exec -it $SINGLE_POD_NAME -- sh /app/migrate.sh