name: Build Docker Container and push to DO Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test_django_job:
    uses: JuanLadeira/kuber-django/.github/workflows/test_django.yaml@master
  docker_build_job:
    runs-on: ubuntu-latest
    needs: [test_django_job]
    defaults:
      run:
        working-directory: ./web
    env:
      DJANGO_SECRET_KEY: ACasyeh--f3yERcSsNW4YhoaWJ-ChNMuJoLGAx2CiuQ
 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_API_TOKEN_KEY }}
    - name: Login to Do container registry with short-lived credencials
      run: doctl regestry login --expire-seconds 1200
    - name: build container image
      working-directory: ./web
      run:
        docker build -f Dockerfile \ 
           -t registry.digitalocean.com/k8s-django/django-k8s-web:latest \
           -t registry.digitalocean.com/k8s-django/django-k8s-web:${ GITHUB_SHA::7 } \
            . 
    - name: push image to container registry
      run:
        docker push registry.digitalocean.com/k8s-django/django-k8s-web --all-tags